apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-cicd-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-cicd
  template:
    metadata:
      labels:
        app: test-cicd
    spec:
      containers:
        - image: 361769599621.dkr.ecr.us-east-1.amazonaws.com/testimage:latest
          imagePullPolicy: Always
          name: test-cicd
          ports:
            - containerPort: 3000

            
apiVersion: v1
kind: Service
metadata:
  name: cicd-demo
spec:
  selector:
    app: test-cicd
  type: LoadBalancer
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 3000            
